use embedded_graphics::{
    Drawable,
    image::{Image, ImageRaw},
    pixelcolor::BinaryColor,
    prelude::{DrawTarget, Point},
};

// Packed 1bpp bitmap generated by build.rs from assets/splash.png (128×64 = 1024 bytes).
// MSB of each byte is the leftmost pixel, matching ImageRaw<BinaryColor> big-endian layout.
const SPLASH_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/splash.bin"));

pub struct InitScreen;

impl InitScreen {
    pub fn new() -> Self {
        Self
    }

    pub fn render(&self, target: &mut impl DrawTarget<Color = BinaryColor>) {
        let raw = ImageRaw::<BinaryColor>::new(SPLASH_BYTES, 128);
        let _ = Image::new(&raw, Point::zero()).draw(target);
    }
}
